<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>NetFluss.App</RootNamespace>
    <AssemblyName>NetFluss</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NetFluss.Core/NetFluss.Core.csproj" />
    <ProjectReference Include="../NetFluss.Native/NetFluss.Native.csproj" />
    <ProjectReference Include="../NetFluss.Tray/NetFluss.Tray.csproj" />
  </ItemGroup>

</Project>
